Describe 'Media Module' {
    BeforeAll {
        # Import the entire Media module
        Import-Module '.\Modules\Media\MediaTools.psm1' -Force
    }
    # Import individual function tests
    # TODO: Add Media function tests as they are created
    # . "$PSScriptRoot\Media\Add-MediaStream.Tests.ps1"
    # . "$PSScriptRoot\Media\Add-PlexFolder.Tests.ps1"
    # . "$PSScriptRoot\Media\Convert-ToConstantFrameRate.Tests.ps1"
    # . "$PSScriptRoot\Media\ConvertTo-MediaStreamCollection.Tests.ps1"
    # . "$PSScriptRoot\Media\Export-AudioStream.Tests.ps1"
    # . "$PSScriptRoot\Media\Export-Chapter.Tests.ps1"
    # . "$PSScriptRoot\Media\Export-MediaStream.Tests.ps1"
    # . "$PSScriptRoot\Media\Export-MediaStreamCollection.Tests.ps1"
    # . "$PSScriptRoot\Media\Export-MediaStreams.Tests.ps1"
    # . "$PSScriptRoot\Media\Export-SubtitleStream.Tests.ps1"
    # . "$PSScriptRoot\Media\Find-StringInFiles.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-AudioData.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-AudioMetadataMap.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-AudioStream.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-Bitrate.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-Bitrates.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-ChapterInfo.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-EnhancedTitle.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-EpisodeInfoFromFilename.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-FFMpegVersion.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-MediaExtension.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-MediaStats.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-MediaStream.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-MediaStreamCollection.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-MediaStreams.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-MkvTrack.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-MkvTrackAll.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-MkvTracks.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-MultipleAudioStreams.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-SubtitleStream.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-SystemSnapshot.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-TvDbEpisodeIds.Tests.ps1"
    # . "$PSScriptRoot\Media\Get-TvDbEpisodeInfo.Tests.ps1"
    # . "$PSScriptRoot\Media\Invoke-CaptionExtraction.Tests.ps1"
    # . "$PSScriptRoot\Media\Invoke-ChapterExtraction.Tests.ps1"
    # . "$PSScriptRoot\Media\Invoke-CheckedCommand.Tests.ps1"
    # . "$PSScriptRoot\Media\Invoke-FFMpeg.Tests.ps1"
    # . "$PSScriptRoot\Media\Invoke-FFProbe.Tests.ps1"
    # . "$PSScriptRoot\Media\Invoke-PlexFileOperation.Tests.ps1"
    # . "$PSScriptRoot\Media\Invoke-Process.Tests.ps1"
    # . "$PSScriptRoot\Media\Invoke-SafeFileRename.Tests.ps1"
    # . "$PSScriptRoot\Media\Invoke-VideoCopy.Tests.ps1"
    # . "$PSScriptRoot\Media\Move-PlexFile.Tests.ps1"
    # . "$PSScriptRoot\Media\Remove-PlexEmptyFolder.Tests.ps1"
    # . "$PSScriptRoot\Media\Resolve-InputPath.Tests.ps1"
    # . "$PSScriptRoot\Media\Show-AudioData.Tests.ps1"
    # . "$PSScriptRoot\Media\Show-MultipleAudioStreams.Tests.ps1"
    # . "$PSScriptRoot\Media\Show-SystemSnapshot.Tests.ps1"
    # . "$PSScriptRoot\Media\Start-SystemMonitoring.Tests.ps1"
}
